In [1]:
from keras.datasets import mnist

#download mnist data and split into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [25]:
import matplotlib.pyplot as plt

#plot the first image in the dataset
# plt.imshow(X_train[0])

#check image shape
# X_train[0].shape

In [3]:
#reshape data to fit model
# liczba zdjęć, rozmiar x (zdjęcia), rozmiar y (zdjęcia), liczba kolorów (1 - odcienie szarości)
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)

In [4]:
from keras.utils import to_categorical

#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

#create model
model = Sequential()

#add model layers
# 64 - liczba neuronów, kernel_size - maska 3x3,
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
# warstwa łącząca conv2d z warstwą dense
model.add(Flatten())
# liczba taka ile wyjść, tu 10 liczb (u mnie będzie 6 wyjść bo tyle jest typów)
model.add(Dense(10, activation='softmax'))

In [6]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
# sprawdzanie danych
import numpy as np
# x = np.reshape(y_test[0], (28, 28))
y_test


array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [7]:
#train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 195s 3ms/step - loss: 0.2718 - accuracy: 0.9499 - val_loss: 0.1050 - val_accuracy: 0.9708
Epoch 2/3
60000/60000 [==============================] - 171s 3ms/step - loss: 0.0729 - accuracy: 0.9774 - val_loss: 0.0896 - val_accuracy: 0.9742
Epoch 3/3
60000/60000 [==============================] - 165s 3ms/step - loss: 0.0471 - accuracy: 0.9856 - val_loss: 0.0841 - val_accuracy: 0.9756


In [8]:
#predict first 4 images in the test set
model.predict(X_test[:4])

array([[1.1848853e-08, 2.2700432e-14, 3.0765887e-07, 5.9313885e-07,
        3.1385985e-12, 2.9493644e-11, 2.9017685e-14, 9.9999893e-01,
        6.1579264e-08, 1.9135035e-08],
       [4.6868930e-08, 1.1041980e-09, 9.9999702e-01, 2.1850438e-08,
        2.4930513e-13, 1.2050764e-12, 2.9741175e-06, 1.5546831e-11,
        1.4963981e-09, 3.7647618e-11],
       [1.9280762e-06, 9.9916220e-01, 2.4116483e-05, 2.8898270e-07,
        4.6397072e-05, 2.5331095e-05, 1.4011457e-05, 8.6875201e-07,
        7.2493491e-04, 8.0218179e-09],
       [9.9976331e-01, 1.1037893e-11, 1.4737496e-05, 9.2565267e-10,
        1.1407944e-08, 9.8032116e-09, 2.0496795e-04, 1.5067270e-09,
        1.3802621e-07, 1.6803227e-05]], dtype=float32)

In [9]:
#actual results for first 4 images in test set
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)